apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: rjayb2b/frontend:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-1
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32005
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rjayb2b/backend:latest
        ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-1
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32001
  type: NodePort

